ignored = ["github.com/codelingo/lingo/_examples"]

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.1"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "~1.20.0"

[[constraint]]
  name = "github.com/codelingo/clql"
  source = "git@github.com:codelingo/clql.git"

[[constraint]]
  name = "github.com/codelingo/platform"
  source = "git@github.com:codelingo/platform.git"

[[constraint]]
  name = "github.com/fatih/color"
  version = "~1.5.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/gogits/go-gogs-client"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/hishboy/gocommons"

[[constraint]]
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/juju/errors"

[[constraint]]
  name = "github.com/juju/testing"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pmezard/go-difflib"

[[constraint]]
  name = "github.com/waigani/diffparser"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.5.0"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.1"

[[constraint]]
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/yaml.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/rhysd/go-github-selfupdate"
